Review changes
sixayed/CS-nsu pull request #1
Opened 2023-11-18 10:53 UTC by sixayed

2023-11-18 14:58 UTC, ankirsansan requested changes
.

2023-11-18 14:58 UTC, ankirsansan commented on RomanCollisium/CollisiumApp/CollisiumApp.csproj
>        <PackageReference Include="FluentAssertions" Version="7.0.0-alpha.1" />
Чревато использовать пререлизные либы, если только не целенаправленно это делаешь

2023-11-18 14:58 UTC, ankirsansan commented on RomanCollisium/Core/Services/Sandbox.cs
>      private bool CardsDraft(Deck deck)
Кажется не смысла deck передавать в аргументе, если она живет одна в рамках данного класса (_deck)

2023-11-18 14:58 UTC, ankirsansan commented on RomanCollisium/Core/Services/Sandbox.cs
> +    public readonly ElonPlayer Elon;
Чревато делать игроков публичными полями в данном случае.
Нарушается концепт слабой связности, по идее сюда прилетают игроки как внешняя зависимость и отсюда же они куда то явным образом отдаются.

Было бы лучше в том месте куда ты отдаешь Elon, Mark (ExperimentWorker) или в сам ExperimentWorker загнать игроков как зависимости и получать название стратегии, или как вариант, если не хочешь доп зависимость в ExperimentWorker вносить, добавить в Sandbox методы GetElonStrategyName, GetMarkStrategyName.

Но точно не отдавать игрока полностью

2023-11-18 14:58 UTC, ankirsansan commented on RomanCollisium/Core/Services/Sandbox.cs
>      public void ShowOpponents()
Лучше публичные методы в классе держать выше всех приватных

2023-11-18 14:58 UTC, ankirsansan commented on RomanCollisium/Core/Interfaces/ICardPickStrategy.cs
>  {
В принципе, модификатор доступа public в интерфейсах можно опускать.

2023-11-18 14:58 UTC, ankirsansan commented on RomanCollisium/Core/Models/Deck.cs
> +    private static readonly Card RedCard = new Card(CardColor.Red);
Конструктор в данном случае можно чутка досахарить написание = new(CardColor.Red)

2023-11-18 14:58 UTC, ankirsansan commented on RomanCollisium/Core/Models/Deck.cs
> +    private static readonly Card RedCard = new Card(CardColor.Red);
Именования приватных элементов все таки рекомендуется начинать с символа "_".

А зачем часть ты назвал с _, часть без? Это чем то обосновано?

2023-11-18 14:58 UTC, ankirsansan commented on RomanCollisium/Core/Models/Deck.cs
> +    public String CardsToString()
используй ключевой слово string

2023-11-18 14:58 UTC, ankirsansan commented on RomanCollisium/Core/Models/Deck.cs
> +        StringBuilder str = new StringBuilder();
Здесь тоже замечание по стилю. При инициализации не нужно дважды указывать название класса.
Или var str = new StringBuilder, или StringBuilder str = new()

2023-11-18 14:58 UTC, ankirsansan commented on RomanCollisium/Core/Models/Deck.cs
>      {
По поводу Linq, желательно приучать себя все точки переносить на новую строку, очень длинные условия сложно читаются
_cards
.Take(...)
.ToList()

2023-11-18 14:58 UTC, ankirsansan commented on RomanCollisium/Core/Strategies/PickFirstRedStrategy.cs
> +        for(int i = 0; i < cards.Length; i++)
Попробуй данный цикл переписать на простое Linq выражение

2023-11-18 14:58 UTC, ankirsansan commented on RomanCollisium/DataAccess/Entities/Experiment.cs
> +    [Column(TypeName = "TEXT")] public DateTime Date { get; set; }
Зачем TypeName = "TEXT"?

2023-11-18 14:58 UTC, ankirsansan commented on RomanCollisium/DataAccess/Entities/Experiment.cs
> +public class Experiment
Похвально, что попробовал в 2 таблички сделать, как с тобой проговаривали) 
но попробуй сделать их связными. 
Сейчас они друг от друга никак не зависят, с точки зрения БД и ничего не мешает положить в данные что угодно (к примеру Experiment без ExperimentCondition или наоборот).

У EF очень мощный и одновременно простой инструментарий работы со связными сущностями

2023-11-18 14:58 UTC, ankirsansan commented on RomanCollisium/DataAccess/Entities/Experiment.cs
> +public class Experiment
Сейчас заметил, ты сделал это на уровне ключей, но лучше прописать зависимость на уровне самой сущности. Т.е. в Experiment должно быстро свойство рода List<ExperimentCondition>, в ExperimentCondition свойство рода Experiment

2023-11-18 14:58 UTC, ankirsansan commented on RomanCollisium/DataAccess/Entities/Experiment.cs
> +public class Experiment
https://learn.microsoft.com/ru-ru/ef/core/modeling/relationships

2023-11-18 14:58 UTC, ankirsansan commented on RomanCollisium/DataAccess/Services/ExperimentData.cs
> +    private readonly ExperimentRepository<ExperimentCondition> _conditionsExperimentRepository;
А это вас так учили делать, чтобы вынести понятие DbContext в отдельный сервис?) Или откуда такая практика?)

Просто сразу видится, если проект большой и у тебя 100 таблиц, то сюда придется 100 зависимостей запихивать, что кажется не очень круто

2023-11-18 14:58 UTC, ankirsansan commented on RomanCollisium/DataAccess/Repositories/ExperimentRepository.cs
> +    public void Create(List<TEntity> entities)
Может ExperimentRepository сделать независимым от TEntity, а методы зависимыми? 
Create<TEntity>(List<TEntity> entities) { ... }

Тогда тебе не надо будет для каждой таблички регистрировать отдельный ExperimentRepository

2023-11-18 14:58 UTC, ankirsansan commented on RomanCollisium/Tests/DeckTests.cs
>      public void Init_Correctly()
Раз мы сделали возможность произвольного размера колоды (что хорошо), я бы и тест написал для различных размеров колоды.

вместо [Fact] -> [Theory] и в аргументы передавать число карт. Сделать несколько вариантов 2, 36, 54, 1000 .... Тест останется один, но покрывает больше кейсов

2023-11-18 14:58 UTC, ankirsansan commented on RomanCollisium/Tests/ExperimentDataTests.cs
> +    public ExperimentDataTests(ITestOutputHelper testOutputHelper)
А для чего ITestOutputHelper?

2023-11-18 14:58 UTC, ankirsansan commented on RomanCollisium/CollisiumApp/CollisiumApp.csproj
>        <PackageReference Include="Microsoft.Extensions.Configuration" Version="7.0.0" />
Общий коммент, попробуй исправить все warning-и предложения по всему проекту, что выдает IDE.
Очень полезно порой для понимания и чистоты кода

![image](https://github.com/sixayed/CS-nsu/assets/142854943/f7a02700-c54e-4433-b3af-6ff53b27356e)

2023-11-18 14:58 UTC, ankirsansan commented on RomanCollisium/Tests/ExperimentDataTests.cs
> +        experiment.FirstStrategy.Should().NotBeNullOrEmpty();
Может лучше проверить, что свойство равняется FirstStrategyName?

2023-11-18 14:58 UTC, ankirsansan commented on RomanCollisium/Tests/SandboxTests.cs
>          mockShuffler.Setup(shuffler => shuffler.Shuffle(It.IsAny<Deck>())).Returns(knownDeck);
КАк и ранее писал, по поводу стиля с точками на каждой новой строке

Плюс сам шаффлер мокается в 2-х тестах очень похоже. Лучше сделать какой нибудь приватный метод, который покрывал бы 2 необходимых кейса в тестах. 
Меньше дублирования кода, больше читаемости

2023-11-18 14:58 UTC, ankirsansan commented on RomanCollisium/Tests/StrategyTests.cs
>      public void Pick_FirstCardRed_ReturnsZero()
Тесты с 17, 0 можно объеденить в один, вместо Fact Theory

2023-11-19 08:38 UTC, sixayed commented on RomanCollisium/Core/Models/Deck.cs
> +    private static readonly Card RedCard = new Card(CardColor.Red);
Rider предлагает именно такие имена, для статиков с большой буквы, без _

2023-11-19 09:05 UTC, sixayed commented on RomanCollisium/DataAccess/Entities/Experiment.cs
> +    [Column(TypeName = "TEXT")] public DateTime Date { get; set; }
Я хотел, чтобы в БД дата была представлена именно как текст

2023-11-19 15:37 UTC, sixayed commented on RomanCollisium/DataAccess/Services/ExperimentData.cs
> +    private readonly ExperimentRepository<ExperimentCondition> _conditionsExperimentRepository;
В смысле 100 зависимостей между каждым репозиторием и контекстом? Не очень понимаю в чем проблема, в том что DbContext отдельный класс или то, что связан композицией с каждым репозиторием?

2023-11-29 18:48 UTC, merged